# /usr/share/doc/lighttpd/fastcgi.txt.gz
# http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs:ConfigurationOptions#mod_fastcgi-fastcgi

server.modules += ( "mod_fastcgi" )

fastcgi.server = (   
  "/api/system" => ((  
    "socket" => "/tmp/arsystem-fcgi-socket",
    "check-local" => "disable"
  ))  
) 
