# /usr/share/doc/lighttpd/fastcgi.txt.gz
# http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs:ConfigurationOptions#mod_fastcgi-fastcgi

server.modules += ( "mod_fastcgi" )


fastcgi.server = (   
  ## The script name of the application  
  "/api/system" => ((  
    ## Command line to run  
    "bin-path" => "/usr/sbin/arsystem",  
    "socket" => "/tmp/arsystem-fcgi-socket",  
    ## Important - only one process should start  
    "max-procs" => 1,   
    "check-local" => "disable",
    "kill-signal" => 10,
    "bin-environment" => ( 
#        "ATSC3_DEBUG" => "1",
        )
  ))  
) 
