# /usr/share/doc/lighttpd/fastcgi.txt.gz
# http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs:ConfigurationOptions#mod_fastcgi-fastcgi

server.modules += ( "mod_fastcgi" )

fastcgi.server = (   
  "/api/system" => ((  
    "socket" => "/tmp/arsystem-fcgi-socket",
    "check-local" => "disable"
  ))  
) 

server.modules += ( "mod_proxy" )

$HTTP["url"] =~ "^/api/fpga" {
  proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8000 )))
}

$HTTP["url"] =~ "^/api/caps" {
  proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8000 )))
}

$HTTP["url"] =~ "^/api/login" {
  proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8000 )))
}

$HTTP["url"] =~ "^/api/users" {
  proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8000 )))
}

$HTTP["url"] =~ "^/api/auth" {
  proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8000 )))
}

$HTTP["url"] =~ "^/api/reboot" {
  proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8000 )))
}

$HTTP["url"] =~ "^/api/stats" {
  proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8000 )))
}

$HTTP["url"] =~ "^/api/telemetry" {
  proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8000 )))
}

$HTTP["url"] =~ "^/api/analyzer" {
  proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8000 )))
}

$HTTP["url"] =~ "^/api/status" {
  proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8000 )))
}

$HTTP["url"] =~ "^/api/gateway" {
  proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8000 )))
}