#!/bin/sh

DAEMON="tangelo"
PIDFILE="/var/run/$DAEMON.pid"
export TANGELO_USE_FS=true
export TANGELO_SKIP_AUTH=true
export TANGELO_CFG=/var/lib/tangelo/tangelo.cfg

if [ -f /etc/env.conf ]; then
    source /etc/env.conf
fi

start() {
	printf 'Starting %s: ' "$DAEMON"
	# auto core dump
	ulimit -c unlimited
	start-stop-daemon -S -b -q -m -p "$PIDFILE" --exec "/usr/sbin/$DAEMON" 
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}
stop() {
printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	while start-stop-daemon -K -t -q -p "$PIDFILE" --exec "/usr/sbin/$DAEMON"; do
		sleep 0.1
	done
	rm -f "$PIDFILE"
	return "$status"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

